version: '3.0'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/tls:/etc/nginx/tls
      - ../public:/public
    ports:
      - "443:443"
    restart: always

  mysql:
    cpus: 1
    mem_limit: 1g
    image: mysql/mysql-server:8.0.31
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ../webapp/sql/admin/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    restart: always

volumes:
  mysql:
  gopkg:
  tenant_db:
  initial_data:
