require 'prism'

namespace :rbs do
  task setup: %i[clean collection rbs_inline]
  task check: %i[setup steep_check]

  task :clean do
    sh 'rm', '-rf', 'sig/generated/app.rbs'
    sh 'rm', '-rf', '.gem_rbs_collection/'
  end

  task :collection do
    sh 'bundle', 'exec', 'rbs', 'collection', 'install'#, '--frozen'
  end

  task :rbs_inline do
    sh 'bundle', 'exec', 'rbs-inline', '--output', 'app.rb'
    sh 'bundle', 'exec', 'rbs-inline', '--output', 'sqltrace.rb'
  end

  task :steep_check do
    sh 'bundle', 'exec', 'steep', 'check'
  end
end
