D = Steep::Diagnostic

target :app do
  signature "sig"

  check "app.rb"
  check "sqltrace.rb"

  library "json", "csv", "time", "openssl", "csv"

  configure_code_diagnostics(D::Ruby.all_error)
end
