class Time
  def iso8601: () -> String
end

class Open3
  def self.capture2e: (*String) -> [String, Process::Status]
end

module OpenSSL
  class PKey
    class RSA
      def initialize: (String) -> void
    end
  end
end

class CSV
  def headers: () -> Array[String]
end
